id: P003096
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14531
  title: རྒྱུན་ཤེས་དང་ལམ།
  author: ''
  volumes:
    53f7222bd8a3459785d428d21b606611:
      image_group_id: I1KG15678
      title: ''
      volume_number: 1
      total_pages: 456
