id: P003096
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:40:06.056400
source_metadata:
  id: bdr:W1KG14531
  title: རྒྱུན་ཤེས་དང་ལམ།
  author: ''
  volumes:
    53f7222bd8a3459785d428d21b606611:
      image_group_id: I1KG15678
      title: ''
      volume_number: 1
      total_pages: 456
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
