id: IF2EBA828
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:05:23+00:00'
last_modified: '2022-06-07T17:31:51.677778+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14531
  title: རྒྱུན་ཤེས་དང་ལམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    F995:
      image_group_id: I1KG15678
      title: ''
      total_pages: 456
      order: 1
      base_file: F995.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
